### POST request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Donald Trump Jr",
  "email": "dtrumpjr@example.com",
  "address": "742 Evergreen Terrace, San Jose, CA",
  "dateOfBirth": "1992-09-15",
  "registeredDate": "2026-01-25"
}


###